Repository spokids/GongGong_Server, pull requests merged in 2024-11, with the labels that each got.

#4 [Chore/#3] 도메인 엔티티 설정
  build.gradle
  src/main/java/com/example/gonggong_server/GonggongServerApplication.java
  src/main/java/com/example/gonggong_server/program/api/ProgramController.java
  src/main/java/com/example/gonggong_server/program/application/ProgramService.java
  src/main/java/com/example/gonggong_server/program/domain/entity/Program.java
  src/main/java/com/example/gonggong_server/program/domain/repository/ProgramRepository.java
  src/main/java/com/example/gonggong_server/program/domain/value/Ability.java
  src/main/java/com/example/gonggong_server/program/domain/value/ProvinceName.java
  src/main/java/com/example/gonggong_server/program/domain/value/Type.java
  src/main/java/com/example/gonggong_server/program/infra/repository/JpaProgramRepository.java
  src/main/java/com/example/gonggong_server/review/domain/entity/Review.java
  src/main/java/com/example/gonggong_server/scrap/domain/entity/Scrap.java
  src/main/java/com/example/gonggong_server/user/domain/entity/User.java
Labels: chore

#11 [Feat/#9] : 시군구 및 동 조회 기능 구현
  src/main/java/com/example/gonggong_server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/gonggong_server/global/status/ErrorStatus.java
  src/main/java/com/example/gonggong_server/program/api/ProgramController.java
  src/main/java/com/example/gonggong_server/program/application/ProgramService.java
  src/main/java/com/example/gonggong_server/program/application/response/DongResponseDTO.java
  src/main/java/com/example/gonggong_server/program/application/response/SigunguResponseDTO.java
  src/main/java/com/example/gonggong_server/program/application/service/ProgramService.java
  src/main/java/com/example/gonggong_server/program/domain/repository/ProgramRepository.java
  src/main/java/com/example/gonggong_server/program/exception/ProgramException.java
  src/main/java/com/example/gonggong_server/program/infra/repository/JpaProgramRepository.java
Labels: feat

#12 [Feat/#10] : 프로그램 조회 기능 구현
  src/main/java/com/example/gonggong_server/global/status/ErrorStatus.java
  src/main/java/com/example/gonggong_server/program/api/controller/ProgramController.java
  src/main/java/com/example/gonggong_server/program/api/request/ProgramListRequestDTO.java
  src/main/java/com/example/gonggong_server/program/application/response/ProgramListResponseDTO.java
  src/main/java/com/example/gonggong_server/program/application/service/ProgramService.java
  src/main/java/com/example/gonggong_server/program/domain/repository/ProgramRepository.java
  src/main/java/com/example/gonggong_server/program/infra/repository/JpaProgramRepository.java
Labels: feat

#14 [Feat/#13] : 프로그램 스크랩 기능 구현
  src/main/java/com/example/gonggong_server/global/config/SecurityConfig.java
  src/main/java/com/example/gonggong_server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/gonggong_server/global/jwt/JWTFilter.java
  src/main/java/com/example/gonggong_server/global/jwt/JWTUtil.java
  src/main/java/com/example/gonggong_server/global/status/ErrorStatus.java
  src/main/java/com/example/gonggong_server/program/api/controller/ProgramController.java
  src/main/java/com/example/gonggong_server/program/api/request/ProgramListRequestDTO.java
  src/main/java/com/example/gonggong_server/program/infra/repository/JpaProgramRepository.java
  src/main/java/com/example/gonggong_server/scrap/api/ScrapController.java
  src/main/java/com/example/gonggong_server/scrap/application/service/ScrapService.java
  src/main/java/com/example/gonggong_server/scrap/domain/repository/ScrapRepository.java
  src/main/java/com/example/gonggong_server/scrap/exception/ScrapException.java
  src/main/java/com/example/gonggong_server/scrap/infra/repository/JpaScrapRepository.java
Labels: feat, refactor

#20 [Feat/#15] : 후기 기능 구현
  build.gradle
  src/main/java/com/example/gonggong_server/global/config/S3Config.java
  src/main/java/com/example/gonggong_server/global/config/SecurityConfig.java
  src/main/java/com/example/gonggong_server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/gonggong_server/global/status/ErrorStatus.java
  src/main/java/com/example/gonggong_server/global/util/S3Util.java
  src/main/java/com/example/gonggong_server/review/api/controller/ReviewController.java
  src/main/java/com/example/gonggong_server/review/api/request/ReviewRequestDTO.java
  src/main/java/com/example/gonggong_server/review/application/response/ReviewListResponseDTO.java
  src/main/java/com/example/gonggong_server/review/application/response/ReviewResponseDTO.java
  src/main/java/com/example/gonggong_server/review/application/service/ReviewService.java
  src/main/java/com/example/gonggong_server/review/domain/entity/Review.java
  src/main/java/com/example/gonggong_server/review/domain/repository/ReviewRepository.java
  src/main/java/com/example/gonggong_server/review/exception/ReviewException.java
  src/main/java/com/example/gonggong_server/review/intra/repository/JpaReviewRepository.java
  src/main/java/com/example/gonggong_server/user/domain/repository/UserRepository.java
  src/main/java/com/example/gonggong_server/user/infra/repository/JpaUserRepository.java
Labels: feat

#24 [Feat/#21] : 프로그램 상세 조회 구현 기능
  src/main/java/com/example/gonggong_server/global/config/SecurityConfig.java
  src/main/java/com/example/gonggong_server/program/api/controller/ProgramController.java
  src/main/java/com/example/gonggong_server/program/application/response/ProgramDetailResponseDTO.java
  src/main/java/com/example/gonggong_server/program/application/service/ProgramService.java
Labels: feat

#25 [Feat/#22] : 인기 종목 Top3 조회 및 후기 작성된 프로그램 최신순 조회 기능 구현
  src/main/java/com/example/gonggong_server/program/api/controller/ProgramController.java
  src/main/java/com/example/gonggong_server/program/application/response/ProgramListResponseDTO.java
  src/main/java/com/example/gonggong_server/program/application/service/ProgramService.java
  src/main/java/com/example/gonggong_server/review/domain/repository/ReviewRepository.java
  src/main/java/com/example/gonggong_server/review/intra/repository/JpaReviewRepository.java
  src/main/java/com/example/gonggong_server/scrap/application/service/ScrapService.java
  src/main/java/com/example/gonggong_server/scrap/domain/entity/Scrap.java
  src/main/java/com/example/gonggong_server/scrap/domain/repository/ScrapRepository.java
  src/main/java/com/example/gonggong_server/scrap/infra/repository/JpaScrapRepository.java
Labels: feat

#27 [Feat/#26] 마이페이지 후기리스트 및 후기 삭제
  src/main/java/com/example/gonggong_server/global/config/SecurityConfig.java
  src/main/java/com/example/gonggong_server/global/status/ErrorStatus.java
  src/main/java/com/example/gonggong_server/review/api/controller/ReviewController.java
  src/main/java/com/example/gonggong_server/review/application/response/MyReviewListResponseDTO.java
  src/main/java/com/example/gonggong_server/review/application/service/ReviewService.java
  src/main/java/com/example/gonggong_server/review/domain/repository/ReviewRepository.java
  src/main/java/com/example/gonggong_server/review/intra/repository/JpaReviewRepository.java
Labels: feat

#29 [Refactor/#23] : 프로그램 상세 조회 시 후기 무한 스크롤 구현
  src/main/java/com/example/gonggong_server/review/api/controller/ReviewController.java
  src/main/java/com/example/gonggong_server/review/application/response/ReviewListResponseDTO.java
  src/main/java/com/example/gonggong_server/review/application/service/ReviewService.java
  src/main/java/com/example/gonggong_server/review/domain/repository/ReviewRepository.java
  src/main/java/com/example/gonggong_server/review/intra/repository/JpaReviewRepository.java
Labels: refactor

#31 [Refactor/#30] : 마이페이지 무한스크롤 구현
  src/main/java/com/example/gonggong_server/review/api/controller/ReviewController.java
  src/main/java/com/example/gonggong_server/review/application/response/MyReviewListResponseDTO.java
  src/main/java/com/example/gonggong_server/review/application/service/ReviewService.java
  src/main/java/com/example/gonggong_server/review/domain/repository/ReviewRepository.java
  src/main/java/com/example/gonggong_server/review/intra/repository/JpaReviewRepository.java
  src/main/java/com/example/gonggong_server/scrap/api/controller/ScrapController.java
  src/main/java/com/example/gonggong_server/scrap/application/response/ScrapListResponseDTO.java
  src/main/java/com/example/gonggong_server/scrap/application/service/ScrapService.java
  src/main/java/com/example/gonggong_server/scrap/domain/repository/ScrapRepository.java
  src/main/java/com/example/gonggong_server/scrap/infra/repository/JpaScrapRepository.java
Labels: refactor
